apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
  name: rally-store
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
